name: Create future branch

on:
  schedule:
    - '0 0 1 9 *'

jobs:

  create_future_branch:
    name: Create future branch
    runs-on: ubuntu-latest
    steps:

      - name: Initialize
        uses: actions/checkout@v2

      - name: Create future branch
        run: python .github/create-future-branch.py
