name: Create future branch

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 9 *'

jobs:

  create_future_branch:

    name: Create future branch
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - name: Initialize
        uses: actions/checkout@v2

      - name: Create and initialize future branch
        run: python .github/create-future-branch.py

      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Initialize future branch'
          create_branch: true
